Add mapper using kotlinx serialization
nitrite/nitrite-java pull request #821
Opened 2023-08-05 11:14 UTC by MrNuggelz

This pull request adds a new mapper that uses [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization) instead of jackson.

2023-08-05 15:55 UTC, anidotnet commented
Hi @MrNuggelz thanks a lot for your contribution. Unfortunately, just today I have pushed some significant changes in Nitrite's main branch. Like - build system has been changed to maven, `NitriteMapper` api has been changed. 

Could you please raise this PR against the main branch and change your code according to the recent `NitriteMapper` change? I am extremely sorry for the inconvenience.

2023-08-05 16:14 UTC, anidotnet commented
And while you are implementing kotlinx serialization based `NitriteMapper` would you be so kind to check this issue #815, if you are solution can address the issue mentioned there?

2023-08-06 07:07 UTC, anidotnet requested changes
Could you please make the changes?

2023-08-06 07:07 UTC, anidotnet commented on potassium-nitrite/pom.xml
> +            <version>1.5.1</version>
Could you please move this version declaration in parent pom?

2023-08-06 07:07 UTC, anidotnet commented on potassium-nitrite/pom.xml
> +                <executions>
Please move all plugin config in pluginManagement in parent pom.xml

2023-08-06 07:53 UTC, MrNuggelz commented
Hi [anidotnet](https://github.com/anidotnet). Thanks for the fast review.
I looked into #815 and what would need to be changed. I think the `tryConvert` method from `NitriteMapper` would require an additional parameter for the source class `Class<Source> sourceType`. I am currently trying to implement this.
Also is there a way to ignore some of the lining error from the "Codacy Static Code Analysis"? All of the remaining errors are can't do not make sense/really be fixed.

2023-08-06 08:19 UTC, merged

2023-08-06 08:24 UTC, anidotnet commented
About the Codacy Static Code Analysis. I have addressed high level issues earlier. All Medium and Minor issues has to be addressed based on the context and viability. Rest of them should be ignored. When I get some time, I'll get into it.